services:
  external:
    container_name: svelte-deploy
    image: node-svelte-deploy
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Brussels
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - caddy
networks:
  caddy:
    external: true